# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "build" ]
  pull_request:
    branches: [ "build" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    # Install OpenGL development libraries on Ubuntu
    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libglu1-mesa-dev

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2' # or any other version you need
        host: ${{ matrix.os == 'ubuntu-latest' && 'linux' || 'windows' }}
        target: desktop

    - name: Configure CMake
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake
        else
          CMAKE_PREFIX_PATH=${QT_ROOT_DIR}/lib/cmake
        fi
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH
      shell: bash

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

