name: CMake on Multiple Platforms

on:
  push:
    branches: [ "build" ]
  pull_request:
    branches: [ "build" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        if [ ${{ matrix.os }} = "ubuntu-latest" ]; then
          sudo apt-get update
          sudo apt-get install -y libglu1-mesa-dev
        fi

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: ${{ matrix.os == 'ubuntu-latest' && 'linux' || 'mac' }}
        target: desktop

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

